#!/bin/bash

folder=`df -a | tail -n +2 | sed "s/^.* \([^ ]*$\)/\1/" | grep "^/mnt" | sed "s/^.*\/\([^\/]*$\)/\1/" | dmenu`

response=""

[[ "$folder" != "" ]] && response=`sudo umount /mnt/$folder 2>&1`

[[ "$response" != "" ]] && notify-send "$response"
