#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

source ~/.files/configs/bash/variables.sh
source ~/.files/configs/bash/aliases.sh
source ~/.files/configs/bash/functions.sh

# Check if the system needs to be updated (current: 5 days)
update -b 432000

# Add autocomplete to pandoc
. <(pandoc --bash-completion)

# Tell git about my gpg key
export GPG_TTY=$(tty)

eval "$(rbenv init -)"

# Remind me of all the things that exist
ding

# Remind me to BETAAL MIJN FUCKING SCHULDEN
# tabBalance -s 1.6
