#
# ~/.bash-profile
#

source $HOME/.files/configs/bash/variables.sh
source $HOME/.files/configs/bash/aliases.sh
source $HOME/.files/configs/bash/functions.sh

if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
    exec startx
fi
