#!/bin/bash

cpu_min="800MHz"
cpu_max="4.50GHz"

if [[ "$1" == "min" ]]; then
    sudo cpupower frequency-set --governor powersave > /dev/null &&
    sudo cpupower frequency-set --max $cpu_min > /dev/null &&
    sudo cpupower frequency-info
    exit $?
elif [[ "$1" == "max" ]]; then
    sudo cpupower frequency-set --governor performance > /dev/null &&
    sudo cpupower frequency-set --max $cpu_max > /dev/null &&
    sudo cpupower frequency-info
    exit $?
elif [[ "$1" == "normal" ]]; then
    sudo cpupower frequency-set --governor powersave > /dev/null &&
    sudo cpupower frequency-set --max $cpu_max > /dev/null &&
    sudo cpupower frequency-info
    exit $?
else
    echo "Usage: cpuspeed <new-state> Supported states are:
    - max: $cpu_max (performance)
    - min: $cpu_min (powersave)
    - normal: $cpu_max (powersave)" >&2 
fi
